set(HASH_SRC_FILES
  hashes/donothing.cpp
  hashes/badhash.cpp
  hashes/aesrng.cpp
#
#########################################
# Normal hashes are sorted biggest->smallest to try to minimize
# parallel compilation times
#########################################
#
#  hashes/pmp_multilinear.cpp
  hashes/farmhash.cpp
  hashes/mum_mir.cpp
  hashes/halftimehash.cpp
  hashes/blake3.cpp
  hashes/xxhash.cpp
  hashes/blake2.cpp
  hashes/umash.cpp
  hashes/cityhash.cpp
  hashes/rmd.cpp
  hashes/t1ha.cpp
  hashes/abseil.cpp
  hashes/metrohash.cpp
  hashes/rust-ahash.cpp
  hashes/highwayhash.cpp
  hashes/clhash.cpp
  hashes/discohash.cpp
  hashes/chaskey.cpp
  hashes/siphash.cpp
  hashes/nmhash.cpp
  hashes/ascon.cpp
  hashes/prvhash.cpp
  hashes/vmac.cpp
  hashes/aesrng.cpp
  hashes/meowhash.cpp
  hashes/spookyhash.cpp
  hashes/sha2.cpp
  hashes/rainstorm.cpp
  hashes/sha1.cpp
  hashes/farsh.cpp
  hashes/hasshe2.cpp
  hashes/perlhashes.cpp
  hashes/beamsplitter.cpp
  hashes/khashv.cpp
  hashes/polymur.cpp
  hashes/jodyhash.cpp
  hashes/poly_mersenne.cpp
  hashes/falkhash.cpp
  hashes/fnv.cpp
  hashes/rainbow.cpp
  hashes/wyhash.cpp
  hashes/aquahash.cpp
  hashes/aesnihash-peterrk.cpp
  hashes/md5.cpp
  hashes/murmurhash3.cpp
  hashes/mx3.cpp
  hashes/crc.cpp
  hashes/rapidhash.cpp
  hashes/pearson.cpp
  hashes/multiply_shift.cpp
  hashes/komihash.cpp
  hashes/aesnihash-majek.cpp
  hashes/tabulation.cpp
  hashes/khash.cpp
  hashes/murmurhash2.cpp
  hashes/fletcher.cpp
  hashes/floppsyhash.cpp
  hashes/badhash.cpp
  hashes/seahash.cpp
  hashes/crap.cpp
  hashes/blockpearson.cpp
  hashes/sha3.cpp
  hashes/lookup3.cpp
  hashes/murmurhash1.cpp
  hashes/donothing.cpp
  hashes/rust-fxhash.cpp
  hashes/falcon_oaat.cpp
  hashes/fasthash.cpp
  hashes/pengyhash.cpp
  hashes/superfasthash.cpp
  hashes/o1hash.cpp
  hashes/murmur_oaat.cpp
  hashes/x17.cpp
)
